Repository pangeo-data/climpred, pull requests merged in 2019-05, with the labels that each got.

#105 aaron's commit from refactoring PR
  .travis.yml
  ci/requirements-py36.yml
  climpred/bootstrap.py
  climpred/comparisons.py
  climpred/graphics.py
  climpred/prediction.py
  climpred/relative_entropy.py
  climpred/tests/test_comparisons.py
  climpred/tests/test_perfect_model_prediction.py
  climpred/tests/test_relative_entropy.py
  climpred/tests/test_stats.py
  notebooks/Relative_Entropy_demo.ipynb
  notebooks/object_oriented_demo.ipynb
  notebooks/perfect-model_predictability.ipynb
  setup.py
Labels: cleanup

#119 MPIESM_sample_data
  climpred/comparisons.py
  climpred/loadutils.py
  climpred/metrics.py
  climpred/prediction.py
  climpred/tests/test_loadutils.py
  sample_data/prediction/MPIESM_miklip_baseline1-assim-SST-global.md5
  sample_data/prediction/MPIESM_miklip_baseline1-assim-SST-global.nc
  sample_data/prediction/MPIESM_miklip_baseline1-hind-SST-global.md5
  sample_data/prediction/MPIESM_miklip_baseline1-hind-SST-global.nc
  sample_data/prediction/MPIESM_miklip_baseline1-hist-SST-global.md5
  sample_data/prediction/MPIESM_miklip_baseline1-hist-SST-global.nc
Labels: enhancement, infrastructure

#124 change ReferenceEnsemble to HindcastEnsemble
  climpred/__init__.py
  climpred/classes.py
  climpred/comparisons.py
  notebooks/object_oriented_demo.ipynb
Labels: cleanup

#138 Add proxy option for open_dataset
  climpred/loadutils.py
Labels: bug

#144 Remove xr_ prefix from stats module
  climpred/bootstrap.py
  climpred/prediction.py
  climpred/stats.py
  climpred/tests/test_hindcast_prediction.py
  climpred/tests/test_stats.py
  notebooks/hindcast_prediction_demo.ipynb
  notebooks/object_oriented_demo.ipynb
  notebooks/perfect-model_predictability.ipynb
Labels: cleanup

#139 Add custom exceptions for clearer error reporting.
  climpred/__init__.py
  climpred/bootstrap.py
  climpred/classes.py
  climpred/comparisons.py
  climpred/exceptions.py
  climpred/graphics.py
  climpred/metrics.py
  climpred/prediction.py
  climpred/stats.py
  climpred/tests/test_hindcast_prediction.py
  climpred/tests/test_stats.py
  climpred/utils.py
Labels: cleanup
