Repository pangeo-data/climpred, pull requests merged in 2019-04, with the labels that each got.

#87 AS_cleanup
  .travis.yml
  ci/requirements-py36.yml
  climpred/bootstrap.py
  climpred/graphics.py
  climpred/prediction.py
  climpred/stats.py
  climpred/tests/test_prediction.py
  notebooks/DPLE_hindcast_prediction.ipynb
  notebooks/perfect-model_predictability.ipynb
  setup.py
Labels: cleanup, high priority

#86 Add initial classes/object features.
  climpred/__init__.py
  climpred/bootstrap.py
  climpred/classes.py
  climpred/loadutils.py
  climpred/prediction.py
  notebooks/DPLE_hindcast_prediction.ipynb
  notebooks/Relative_Entropy_demo.ipynb
  notebooks/object_oriented_demo.ipynb
  notebooks/perfect-model_predictability.ipynb
  notebooks/reconstruction_based_prediction_demo.ipynb
  sample_data/prediction/CESM-DP-LE.SSS.global.md5
  sample_data/prediction/CESM-DP-LE.SSS.global.nc
  sample_data/prediction/CESM-DP-LE.SST.annmean.anom.md5
  sample_data/prediction/CESM-DP-LE.SST.annmean.anom.nc
  sample_data/prediction/CESM-DP-LE.SST.global.md5
  sample_data/prediction/CESM-DP-LE.SST.global.nc
  sample_data/prediction/FOSI.SSS.global.md5
  sample_data/prediction/FOSI.SSS.global.nc
  sample_data/prediction/FOSI.SST.global.md5
  sample_data/prediction/FOSI.SST.global.nc
  sample_data/prediction/g.e11_LENS.GECOIAF.T62_g16.009.pop.h.SST.024901-031612.md5
  sample_data/prediction/g.e11_LENS.GECOIAF.T62_g16.009.pop.h.SST.024901-031612.nc
Labels: enhancement, high priority

#98 Update dimensions to intuitive names + refactoring
  .travis.yml
  .unibeautifyrc.yml
  climpred/__init__.py
  climpred/bootstrap.py
  climpred/classes.py
  climpred/comparisons.py
  climpred/graphics.py
  climpred/metrics.py
  climpred/prediction.py
  climpred/stats.py
  climpred/tests/test_comparisons.py
  climpred/tests/test_perfect_model_prediction.py
  climpred/tests/test_prediction.py
  climpred/tests/test_reference_prediction.py
  climpred/tests/test_stats.py
  climpred/utils.py
  notebooks/object_oriented_demo.ipynb
  notebooks/perfect-model_predictability.ipynb
  notebooks/reconstruction_based_prediction_demo.ipynb
Labels: cleanup
