Repository pangeo-data/climpred, pull requests merged in 2019-06, with the labels that each got.

#174 Add sphinx documentation
  .github/PULL_REQUEST_TEMPLATE.md
  .pre-commit-config.yaml
  .travis.yml
  CHANGELOG.rst
  CHANGES.md
  README.md
  README.rst
  ci/docs.yml
  ci/environment-dev-3.6.yml
  climpred/bootstrap.py
  climpred/prediction.py
  climpred/stats.py
  climpred/tutorial.py
  docs/API.rst
  docs/Makefile
  docs/conf.py
  docs/index.rst
  docs/make.bat
  docs/sample_data.rst
  docs/source/api.rst
  docs/source/changelog.rst
  docs/source/comparisons.rst
  docs/source/conf.py
  docs/source/contributing.rst
  docs/source/contributors.rst
  docs/source/examples.rst
  docs/source/examples/Relative_Entropy_demo.ipynb
  docs/source/examples/hindcast_prediction_demo.ipynb
  docs/source/examples/object_oriented_demo.ipynb
  docs/source/examples/perfect-model_predictability.ipynb
  docs/source/images/climpred-logo-inverse.png
  docs/source/images/climpred-logo.png
  docs/source/index.rst
  docs/source/metrics.rst
  docs/source/quick-start.rst
  docs/source/sample-data.ipynb
  docs/source/setting-up-data.rst
  docs/source/terminology.rst
  docs/source/why-climpred.rst
  notebooks/Relative_Entropy_demo.ipynb
  notebooks/hindcast_prediction_demo.ipynb
  notebooks/object_oriented_demo.ipynb
  readthedocs.yml
  setup.py
Labels: don't merge

#175 Add doc build to CI
  .travis.yml
  ci/docs.yml
  ci/environment-dev-3.6.yml
Labels: don't merge

#171 Bf bootstrap couldnt be saved on disk
  climpred/bootstrap.py
  climpred/graphics.py
  climpred/metrics.py
Labels: bug

#181 Aaron add docs
  CHANGELOG.rst
  climpred/comparisons.py
  climpred/metrics.py
  climpred/relative_entropy.py
  climpred/stats.py
  docs/source/api.rst
  docs/source/comparisons.rst
  docs/source/conf.py
  docs/source/examples.rst
  docs/source/examples/Relative_Entropy_demo.ipynb
  docs/source/examples/perfect-model_predictability.ipynb
  docs/source/metrics.rst
  docs/source/terminology.rst
Labels: documentation

#189 Aaron add docs II
  climpred/comparisons.py
  climpred/metrics.py
  climpred/prediction.py
  climpred/stats.py
  docs/source/api.rst
  docs/source/comparisons.rst
  docs/source/index.rst
  docs/source/metrics.rst
Labels: documentation
