Repository pangeo-data/climpred, pull requests merged in 2019-01, with the labels that each got.

#21 Enhancements to prediction module for assimilation DPLE's
  esmtools/prediction.py
  esmtools/stats.py
  notebooks/DPLE_hindcast_prediction.ipynb
  notebooks/perfect-model_predictability.ipynb
  notebooks/stats_demo_and_test.ipynb
  sample_data/prediction/CESM-LE.global_mean.SST.1955-2015.nc
  sample_data/prediction/ERSSTv4.global.mean.nc
Labels: enhancement

#38 PM cleanup
  climpred/prediction.py
  notebooks/perfect-model_predictability.ipynb
  setup.py
Labels: cleanup, high priority

#45 Inclue MAE in prediction module
  README.md
  climpred/prediction.py
  notebooks/perfect-model_predictability.ipynb
Labels: enhancement, high priority

#50 add tests
  climpred/prediction.py
  climpred/tests/test_prediction.py
  setup.py
Labels: enhancement

#49 Add predictability horizon for `compute_reference`
  climpred/prediction.py
  climpred/stats.py
  notebooks/DPLE_hindcast_prediction.ipynb
  notebooks/perfect-model_predictability.ipynb
Labels: don't merge, enhancement, high priority
