Repository pangeo-data/climpred, pull requests merged in 2020-09, with the labels that each got.

#418 comparison keyword for uninitialized bootstrap
  CHANGELOG.rst
  climpred/bootstrap.py
  climpred/classes.py
  climpred/tests/test_hindcastEnsemble_class.py
  climpred/utils.py
Labels: feature request

#431 allow binary verif and (un)init forecasts in hindcast.verify()
  CHANGELOG.rst
  ci/environment-dev-3.6.yml
  climpred/bootstrap.py
  climpred/metrics.py
  climpred/prediction.py
  climpred/tests/conftest.py
  climpred/tests/test_compute_dims.py
  climpred/tests/test_metrics_perfect.py
  climpred/tests/test_probabilistic.py
  requirements.txt
Labels: documentation, feature request

#441 reduce warnings
  climpred/graphics.py
  climpred/metrics.py
  climpred/relative_entropy.py
  climpred/tests/test_metrics_perfect.py
  setup.cfg
Labels: testing

#443 Mean bias reduction .groupby('init.dayofyear')
  CHANGELOG.rst
  climpred/bias_reduction.py
  climpred/classes.py
Labels: bug

#439 many probabilistic doppyo metrics
  CHANGELOG.rst
  ci/environment-dev-3.6.yml
  climpred/classes.py
  climpred/metrics.py
  climpred/prediction.py
  climpred/reference.py
  climpred/tests/conftest.py
  climpred/tests/test_PredictionEnsemble_math.py
  climpred/tests/test_bootstrap.py
  climpred/tests/test_hindcast_prediction.py
  climpred/tests/test_metrics.py
  climpred/tests/test_metrics_perfect.py
  climpred/tests/test_perfect_model_prediction.py
  climpred/tests/test_probabilistic.py
  climpred/tests/test_uninitialized.py
  docs/source/api.rst
  docs/source/api/climpred.classes.HindcastEnsemble.plot.rst
  docs/source/api/climpred.classes.PerfectModelEnsemble.plot.rst
  docs/source/api/climpred.classes.PredictionEnsemble.plot.rst
  docs/source/api/climpred.metrics._contingency.rst
  docs/source/api/climpred.metrics._discrimination.rst
  docs/source/api/climpred.metrics._rank_histogram.rst
  docs/source/api/climpred.metrics._reliability.rst
  docs/source/api/climpred.metrics._rps.rst
  docs/source/metrics.rst
Labels: feature request

#409 PredictionEnsemble.__getitem__
  CHANGELOG.rst
  climpred/classes.py
  climpred/tests/test_PredictionEnsemble_math.py
Labels: infrastructure, usability

#436 Force mandatory kwargs for PerfectModelEnsemble methods.
  CHANGELOG.rst
  ci/requirements/docs.yml
  ci/requirements/environment-dev-3.6.yml
  climpred/bias_reduction.py
  climpred/classes.py
  climpred/prediction.py
  climpred/tests/test_compute_dims.py
  climpred/tests/test_hindcastEnsemble_class.py
  climpred/tests/test_perfectModelEnsemble_class.py
  climpred/tests/test_probabilistic.py
  climpred/tests/test_smoothing.py
  docs/source/alignment.ipynb
  docs/source/api.rst
  docs/source/api/climpred.classes.HindcastEnsemble.bootstrap.rst
  docs/source/api/climpred.classes.HindcastEnsemble.reduce_bias.rst
  docs/source/api/climpred.classes.PerfectModelEnsemble.compute_metric.rst
  docs/source/api/climpred.classes.PerfectModelEnsemble.rst
  docs/source/api/climpred.classes.PerfectModelEnsemble.verify.rst
  docs/source/api/climpred.comparisons._e2c.rst
  docs/source/api/climpred.comparisons._e2o.rst
  docs/source/api/climpred.comparisons._m2c.rst
  docs/source/api/climpred.comparisons._m2e.rst
  docs/source/api/climpred.comparisons._m2m.rst
  docs/source/api/climpred.comparisons._m2o.rst
  docs/source/bias_reduction.ipynb
  docs/source/comparisons.rst
  docs/source/examples/dask/efficient_dask.ipynb
  docs/source/examples/decadal/Significance.ipynb
  docs/source/examples/decadal/diagnose-potential-predictability.ipynb
  docs/source/examples/decadal/perfect-model-predictability-demo.ipynb
  docs/source/examples/decadal/tropical-pacific-ssts.ipynb
  docs/source/examples/monseas/monthly-enso-subx-example.ipynb
  docs/source/examples/monseas/seasonal-enso-subx-example.ipynb
  docs/source/examples/preprocessing/setup_your_own_data.ipynb
  docs/source/examples/subseasonal/daily-subx-example.ipynb
  docs/source/examples/subseasonal/weekly-subx-example.ipynb
  docs/source/index.rst
  docs/source/metrics.rst
  docs/source/prediction-ensemble-object.ipynb
  docs/source/quick-start.ipynb
  docs/source/smoothing.ipynb
Labels: cleanup, documentation

#456 cleanup inside metric and comparisons
  CHANGELOG.rst
  climpred/bootstrap.py
  climpred/comparisons.py
  climpred/metrics.py
  climpred/prediction.py
  climpred/reference.py
  climpred/tests/test_comparisons.py
  climpred/tests/test_compute_dims.py
  climpred/tests/test_metrics.py
  climpred/tests/test_metrics_perfect.py
  climpred/tests/test_utils.py
  docs/source/metrics.rst
Labels: cleanup

#461 dont enforce control in verify, only persistence, passes fake control
  CHANGELOG.rst
  climpred/classes.py
  climpred/comparisons.py
  climpred/prediction.py
  climpred/tests/test_perfectModelEnsemble_class.py
Labels: cleanup, usability
