Repository pangeo-data/climpred, pull requests merged in 2020-03, with the labels that each got.

#330 As bootstrap from control cftime
  CHANGELOG.rst
  climpred/bootstrap.py
  climpred/comparisons.py
  climpred/constants.py
  climpred/prediction.py
Labels: cleanup

#328 Refactor same inits
  CHANGELOG.rst
  climpred/bootstrap.py
  climpred/prediction.py
  climpred/tests/conftest.py
  climpred/tests/test_alignment.py
  climpred/tests/test_effective_p_value.py
  climpred/tests/test_hindcastEnsemble_class.py
  climpred/tests/test_lead_time_resolutions.py
  climpred/tests/test_logging.py
  climpred/tests/test_logging_hindcast.py
  climpred/tests/test_utils.py
  climpred/utils.py
  docs/source/alignment.rst
  docs/source/images/alignment_plots/make_alignment_plots.ipynb
  docs/source/images/alignment_plots/same_inits_alignment.png
  docs/source/index.rst
Labels: documentation, feature request, infrastructure

#333 reduce warnings in tests
  CHANGELOG.rst
  climpred/comparisons.py
  climpred/tests/test_bootstrap.py
  climpred/tests/test_hindcastEnsemble_class.py
  climpred/tests/test_metrics.py
  climpred/tests/test_perfectModelEnsemble_class.py
  climpred/tests/test_perfect_model_prediction.py
  climpred/tests/test_preprocessing.py
  climpred/tests/test_probabilistic.py
  climpred/utils.py
  climpred/versioning/print_versions.py
  setup.cfg
Labels: infrastructure, low priority, testing

#331 Add common verification alignment
  CHANGELOG.rst
  climpred/alignment.py
  climpred/bootstrap.py
  climpred/constants.py
  climpred/exceptions.py
  climpred/prediction.py
  climpred/tests/conftest.py
  climpred/tests/test_alignment.py
  climpred/tests/test_bootstrap.py
  climpred/tests/test_hindcastEnsemble_class.py
  climpred/tests/test_hindcast_prediction.py
  climpred/tests/test_perfectModelEnsemble_class.py
  climpred/tests/test_uninitialized.py
  climpred/utils.py
  docs/source/alignment.rst
  docs/source/images/alignment_plots/make_alignment_plots.ipynb
  docs/source/images/alignment_plots/same_inits_alignment.ipynb
  docs/source/images/alignment_plots/same_inits_alignment.png
  docs/source/images/alignment_plots/same_verifs_alignment.ipynb
  docs/source/images/alignment_plots/same_verifs_alignment.png
  docs/source/prediction-ensemble-object.ipynb
Labels: cleanup, documentation, don't merge, feature request, high priority, infrastructure

#338 Add `maximize` keyword for alignment
  CHANGELOG.rst
  climpred/alignment.py
  climpred/bootstrap.py
  climpred/classes.py
  climpred/constants.py
  climpred/logging.py
  climpred/prediction.py
  climpred/tests/test_alignment.py
  climpred/tests/test_bootstrap.py
  climpred/tests/test_lead_time_resolutions.py
  climpred/tests/test_logging.py
  climpred/tests/test_metrics.py
  climpred/tests/test_perfect_model_prediction.py
  climpred/tests/test_utils.py
  climpred/utils.py
  docs/source/alignment.ipynb
  docs/source/alignment.rst
  docs/source/examples/subseasonal/daily-subx-example.ipynb
  docs/source/examples/subseasonal/weekly-subx-example.ipynb
  docs/source/images/alignment_plots/maximize_alignment.ipynb
  docs/source/images/alignment_plots/maximize_alignment.png
  docs/source/images/alignment_plots/same_inits_alignment.ipynb
  docs/source/images/alignment_plots/same_inits_alignment.png
  docs/source/images/alignment_plots/same_verifs_alignment.ipynb
  docs/source/images/alignment_plots/same_verifs_alignment.png
  docs/source/index.rst
  docs/source/savefig/different_alignment_methods.png
Labels: cleanup, documentation, don't merge, feature request

#332 As bootstrap pm control cftime
  CHANGELOG.rst
  ci/environment-dev-3.6.yml
  climpred/bootstrap.py
  climpred/classes.py
  climpred/constants.py
  climpred/prediction.py
  climpred/tests/conftest.py
  climpred/tests/test_bootstrap.py
  climpred/tests/test_compute_dims.py
  climpred/tests/test_probabilistic.py
  climpred/tests/test_utils.py
  climpred/utils.py
Labels: feature request, infrastructure

#341 Refactor prediction module
  CHANGELOG.rst
  ci/environment-dev-3.6.yml
  climpred/alignment.py
  climpred/bootstrap.py
  climpred/classes.py
  climpred/prediction.py
  climpred/reference.py
  climpred/tests/test_alignment.py
  climpred/tests/test_hindcastEnsemble_class.py
  climpred/tests/test_hindcast_prediction.py
  climpred/tests/test_metrics.py
  climpred/tests/test_perfect_model_prediction.py
  climpred/tests/test_uninitialized.py
  docs/source/alignment.ipynb
  docs/source/examples/decadal/Significance.ipynb
  docs/source/examples/decadal/diagnose-potential-predictability.ipynb
  docs/source/examples/decadal/perfect-model-predictability-demo.ipynb
  docs/source/examples/decadal/smoothing.ipynb
  docs/source/examples/decadal/tropical-pacific-ssts.ipynb
  docs/source/examples/subseasonal/daily-subx-example.ipynb
  docs/source/examples/subseasonal/weekly-subx-example.ipynb
  docs/source/prediction-ensemble-object.ipynb
  docs/source/quick-start.ipynb
Labels: cleanup, high priority, infrastructure
