Repository pangeo-data/climpred, pull requests merged in 2020-05, with the labels that each got.

#361 update Aaron and Riley's publications
  docs/source/publications.rst
Labels: documentation

#355 refactor bootstrap: first resample, then metric
  CHANGELOG.rst
  asv_bench/benchmarks/benchmarks_hindcast.py
  asv_bench/benchmarks/benchmarks_perfect_model.py
  climpred/alignment.py
  climpred/bootstrap.py
  climpred/checks.py
  climpred/comparisons.py
  climpred/prediction.py
  climpred/reference.py
  climpred/relative_entropy.py
  climpred/tests/test_bootstrap.py
  climpred/tests/test_checks.py
  climpred/tests/test_preprocessing.py
  climpred/utils.py
  docs/source/examples/decadal/Significance.ipynb
Labels: performance

#371 html repr
  CHANGELOG.rst
  climpred/classes.py
  climpred/reference.py
  climpred/tests/test_repr.py
Labels: visualization
