Repository pangeo-data/climpred, pull requests merged in 2020-01, with the labels that each got.

#283 Add effective p value metric, expand metrics docs.
  .pre-commit-config.yaml
  CHANGELOG.rst
  README.rst
  ci/environment-dev-3.6.yml
  climpred/bootstrap.py
  climpred/classes.py
  climpred/graphics.py
  climpred/metrics.py
  climpred/np_metrics.py
  climpred/stats.py
  climpred/tests/test_effective_p_value.py
  climpred/tests/test_hindcast_prediction.py
  climpred/tests/test_metrics.py
  climpred/tests/test_perfect_model_prediction.py
  docs/source/conf.py
  docs/source/examples/perfect-model-predictability-demo.ipynb
  docs/source/examples/tropical-pacific-ssts.ipynb
  docs/source/index.rst
  docs/source/metrics.rst
  docs/source/prediction-ensemble-object.ipynb
  docs/source/terminology.rst
  requirements.txt
  setup.cfg
Labels: bug, cleanup, documentation, don't merge

#290 resolve stack dims
  CHANGELOG.rst
  climpred/bootstrap.py
  climpred/comparisons.py
  climpred/constants.py
  climpred/prediction.py
  climpred/tests/test_comparisons.py
  climpred/tests/test_compute_dims.py
  climpred/tests/test_effective_p_value.py
  climpred/tests/test_probabilistic.py
  climpred/tests/test_utils.py
  docs/source/comparisons.rst
  docs/source/index.rst
Labels: bug, cleanup

#315 remove circular dependencies
  climpred/bootstrap.py
  climpred/checks.py
  climpred/comparisons.py
  climpred/constants.py
  climpred/graphics.py
  climpred/metrics.py
  climpred/prediction.py
  climpred/tests/test_comparisons.py
  climpred/tests/test_compute_dims.py
  climpred/tests/test_effective_p_value.py
  climpred/tests/test_hindcast_prediction.py
  climpred/tests/test_metrics.py
  climpred/tests/test_perfect_model_prediction.py
  climpred/tests/test_probabilistic.py
  climpred/tests/test_utils.py
  climpred/utils.py
Labels: cleanup, infrastructure

#313 pytest refactor
  CHANGELOG.rst
  HOWTOCONTRIBUTE.rst
  climpred/tests/conftest.py
  climpred/tests/test_checks.py
  climpred/tests/test_comparisons.py
  climpred/tests/test_compute_dims.py
  climpred/tests/test_demo_data.py
  climpred/tests/test_effective_p_value.py
  climpred/tests/test_graphics.py
  climpred/tests/test_hindcastEnsemble_class.py
  climpred/tests/test_hindcast_prediction.py
  climpred/tests/test_metrics.py
  climpred/tests/test_perfectModelEnsemble_class.py
  climpred/tests/test_perfect_model_prediction.py
  climpred/tests/test_probabilistic.py
  climpred/tests/test_relative_entropy.py
  climpred/tests/test_smoothing.py
  climpred/tests/test_stats.py
  climpred/tests/test_utils.py
  climpred/tests/test_versioning.py
  climpred/tests/test_xarray_methods.py
Labels: cleanup, infrastructure
